---
title: "Computerphile Data Analysis Series"
output: html_notebook
---

# 0. Introduction to Data Analysis
* Data Analysis
* Big Data 
* Machine Learning
* Artificial Intelligence
* Clustering
* Data Mining
* Data Pre-processing

If we need to extract value from data, we need a formal set of tools to avail of the information within it, this is data science.

Machine Learning is a subset of AI, the fact that you train a machine to do something from data, so you train it up from nothing using examples from data. AI is often rule based, and the agent doesn't learn.
 
 
Data frames are like tables in excel, except you've also got headings for columns unlike excel.

```{r}
airlineData <- airmiles
studentData <- as.data.frame(HairEyeColor)
par(mfrow = c(1,2))
print(studentData$Hair)
plot(airlineData)

```

* Data Analysis: Using statistical analysis to figure out what's going on  
* Data Visualisation: Plotting and chart to figure out what is going on  
* Pre-process: Weed out the data to drill down to what is the most important parts of information  
* Data Modelling: Predicting from the data what is going to happen e.g. Looking at products online and predict what you want to buy 
* Data Mining: Extract Data from a given source  
* Big Data: When we collect a hige number of examples, and/or each of our examples has a very large amount of variables. It is typically data that we can't feasibly run on our laptops  

# 1. What is data  
* Data has to be measurable

## Four types of data
* __N__
* __O__
* __I__
* __R__